
SET foreign_key_checks = 0;

LOAD DATA LOCAL INFILE "C:\\Users\\mwitt_cjbzle6\\Google Drive\\Teaching\\CSCI 440\\COMPANY database setup\\COMPANY tables\\EMPLOYEE.csv"
INTO TABLE COMPANY.EMPLOYEE
FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\'
LINES TERMINATED BY '\r\n' STARTING BY ''
IGNORE 1 LINES
;

LOAD DATA LOCAL INFILE "C:\\Users\\mwitt_cjbzle6\\Google Drive\\Teaching\\CSCI 440\\COMPANY database setup\\COMPANY tables\\DEPARTMENT.csv"
INTO TABLE COMPANY.DEPARTMENT
FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\'
LINES TERMINATED BY '\r\n' STARTING BY ''
IGNORE 1 LINES
;

LOAD DATA LOCAL INFILE "C:\\Users\\mwitt_cjbzle6\\Google Drive\\Teaching\\CSCI 440\\COMPANY database setup\\COMPANY tables\\DEPT_LOCATION.csv"
INTO TABLE COMPANY.DEPT_LOCATION
FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\'
LINES TERMINATED BY '\r\n' STARTING BY ''
IGNORE 1 LINES
;

LOAD DATA LOCAL INFILE "C:\\Users\\mwitt_cjbzle6\\Google Drive\\Teaching\\CSCI 440\\COMPANY database setup\\COMPANY tables\\WORKS_ON.csv"
INTO TABLE COMPANY.WORKS_ON
FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\'
LINES TERMINATED BY '\r\n' STARTING BY ''
IGNORE 1 LINES
;

LOAD DATA LOCAL INFILE "C:\\Users\\mwitt_cjbzle6\\Google Drive\\Teaching\\CSCI 440\\COMPANY database setup\\COMPANY tables\\PROJECT.csv"
INTO TABLE COMPANY.PROJECT
FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\'
LINES TERMINATED BY '\r\n' STARTING BY ''
IGNORE 1 LINES
;

LOAD DATA LOCAL INFILE "C:\\Users\\mwitt_cjbzle6\\Google Drive\\Teaching\\CSCI 440\\COMPANY database setup\\COMPANY tables\\DEPENDENT.csv"
INTO TABLE COMPANY.DEPENDENT
FIELDS TERMINATED BY ',' ENCLOSED BY '"' ESCAPED BY '\\'
LINES TERMINATED BY '\r\n' STARTING BY ''
IGNORE 1 LINES
;

