-- MySQL Script generated by MySQL Workbench
-- Sun Oct  1 19:55:52 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema COMPANY
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema COMPANY
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `COMPANY` DEFAULT CHARACTER SET utf8 ;
USE `COMPANY` ;

-- -----------------------------------------------------
-- Table `COMPANY`.`DEPARTMENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMPANY`.`DEPARTMENT` (
  `Dname` VARCHAR(45) NOT NULL,
  `Dnumber` INT NOT NULL,
  `Mgr_ssn` INT NOT NULL,
  `Mgr_start_date` DATE NOT NULL,
  PRIMARY KEY (`Dnumber`),
  INDEX `Mgr_ssn_idx` (`Mgr_ssn` ASC),
  CONSTRAINT `Mgr_ssn`
    FOREIGN KEY (`Mgr_ssn`)
    REFERENCES `COMPANY`.`EMPLOYEE` (`Ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COMPANY`.`EMPLOYEE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMPANY`.`EMPLOYEE` (
  `Fname` VARCHAR(45) NOT NULL,
  `Minit` CHAR NULL,
  `Lname` VARCHAR(45) NOT NULL,
  `Ssn` INT(11) NOT NULL,
  `Bdate` DATE NOT NULL,
  `Address` VARCHAR(100) NOT NULL,
  `Sex` CHAR NULL,
  `Salary` INT(11) NOT NULL,
  `Super_ssn` INT(11) NULL,
  `Dno` INT(11) NOT NULL,
  PRIMARY KEY (`Ssn`),
  INDEX `Ssn_idx` (`Super_ssn` ASC),
  INDEX `Dno_idx` (`Dno` ASC),
  CONSTRAINT `Super_ssn`
    FOREIGN KEY (`Super_ssn`)
    REFERENCES `COMPANY`.`EMPLOYEE` (`Ssn`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `Dno`
    FOREIGN KEY (`Dno`)
    REFERENCES `COMPANY`.`DEPARTMENT` (`Dnumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COMPANY`.`DEPENDENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMPANY`.`DEPENDENT` (
  `Essn` INT NOT NULL,
  `Dependent_name` VARCHAR(45) NOT NULL,
  `Sex` CHAR NULL,
  `Bdate` DATE NOT NULL,
  `Relationship` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Essn`, `Dependent_name`),
  CONSTRAINT `Essn`
    FOREIGN KEY (`Essn`)
    REFERENCES `COMPANY`.`EMPLOYEE` (`Ssn`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COMPANY`.`PROJECT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMPANY`.`PROJECT` (
  `Pname` VARCHAR(45) NOT NULL,
  `Pnumber` INT NOT NULL,
  `Plocation` VARCHAR(45) NOT NULL,
  `Dnum` INT NOT NULL,
  PRIMARY KEY (`Pnumber`, `Plocation`),
  INDEX `Dnum_idx` (`Dnum` ASC),
  UNIQUE INDEX `Pname_UNIQUE` (`Pname` ASC),
  UNIQUE INDEX `Pnumber_UNIQUE` (`Pnumber` ASC),
  CONSTRAINT `Dnum`
    FOREIGN KEY (`Dnum`)
    REFERENCES `COMPANY`.`DEPARTMENT` (`Dnumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COMPANY`.`WORKS_ON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMPANY`.`WORKS_ON` (
  `Essn` INT NOT NULL,
  `Pno` INT NOT NULL,
  `Hours` INT NULL,
  INDEX `Pnumber_idx` (`Pno` ASC),
  CONSTRAINT `Ssn`
    FOREIGN KEY (`Essn`)
    REFERENCES `COMPANY`.`EMPLOYEE` (`Ssn`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Pnumber`
    FOREIGN KEY (`Pno`)
    REFERENCES `COMPANY`.`PROJECT` (`Pnumber`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COMPANY`.`DEPT_LOCATION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMPANY`.`DEPT_LOCATION` (
  `Dnumber` INT NOT NULL,
  `Dlocation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Dnumber`, `Dlocation`),
  CONSTRAINT `Dnumber`
    FOREIGN KEY (`Dnumber`)
    REFERENCES `COMPANY`.`DEPARTMENT` (`Dnumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


